from scenesfinal import *
ar=[S1,S2,S3,S4,S5,S6,S7] ## array of scenes funcs
dtime = 0.0045 # delta_time (try 0.005 and 0.00005)
xi=.85 # key x translation
yi=-.15 # key y translation
xn=0
yn=0
but = False # key caught check
xp=0
yp=0
vbasic=2.9
v_velocity = vbasic # Vertical Velocity of the ball
xmov=.005*1.5 # x speed for the player
mov=0 # player y translation
xd=0 # player x translation
width=600
hight=600
w=width//2
h=hight//2
ju=False ## to know if he is jumping or not
again=True ## to prevent character from double jumping
swapedr=False
swapedl=False
swapedup=False
i=0
keyi=i
keys={'w':False,'d':False,'a':False,'f':False,'u':False,'j':False,"up":False,"down":False,"enter":False,"escape":False,'p':False}
catch=True ## to check if the key is catched or not
caught=False
xm=0
ym=0
ironman=False
upsc2=0
door=[False,False,False,False,False,False,False]
angle=0
started=False
xc=0
yc=0
p=1
options=False
credits=False
sound=True
paused=False
fin=False
